# Generated by Django 5.2.7 on 2025-10-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN TRANSIT', 'In transit'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10),
        ),
    ]
