# Generated by Django 5.2.7 on 2025-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_alter_vendorinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN TRANSIT', 'In transit'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10),
        ),
    ]
