# Generated by Django 5.2.7 on 2025-10-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_alter_customerinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('IN TRANSIT', 'In transit'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('IN TRANSIT', 'In transit'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
