# Generated by Django 5.2.7 on 2025-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_alter_customerinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('IN_TRANSIT', 'In Transit')], default='OUTSTANDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PROCESSED', 'Processed')], default='OUTSTANDING', max_length=20),
        ),
    ]
