# Generated by Django 5.2.7 on 2025-10-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_customerinvoice_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
