# Generated by Django 5.2.7 on 2025-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_customer_profile_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='CustomUser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
